default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: password

development:
  <<: *default
  database: budget-app

test:
  <<: *default
  database: budget-test

production:
  <<: *default
  database: budget-dev
